import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Providers from "@/lib/providers";
import { cn } from "@/lib/utils";

const aspekta = localFont({
  src: "./fonts/AspektaVF.woff2",
  variable: "--font-aspekta",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-instrument-serif",
  display: "swap",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Ashwin Parande",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased  dark:bg-neutral-900 bg-amber-50  dark:text-white text-black w-full",
          inter.variable,
          aspekta.variable,
          instrumentSerif.variable
        )}
      >
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
