import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Providers from "@/lib/providers";

const Inter = localFont({
  src: "./fonts/InterVariable.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ashwin Parande",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Inter.className} antialiased mt-32 dark:bg-dark-bg bg-white pb-12 dark:text-white text-black`}
      >
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
